### ISSUE TITLE
Login Page not there

### ISSUE THREAD

**Issue by ProgrammerAditya36** [narainkarthikv/Sticky-Memo#26]
I think I can add a Login page for users to login and store the data. I can do it using MongoDB, PostgresSQL or also using Firebase . which is fine>

**Comment by narainkarthikv** [comment]
@ProgrammerAditya36, I believe Firebase works well for our needs. If you can suggest a better user-based integration within the repository, feel free to do so. However, since this is primarily a frontend application, I think local storage is sufficient for most users. If you're interested in working on a login page, check out my `Fit-Track` application, which has an open issue for login page optimization.

**Comment by ProgrammerAditya36** [comment]
Ok
